---
word_document: default
author: "Beatriz Milz"
date: "08/05/2020"
output:
  html_document: null
 # word_document: default
code_folding: hide
title: "Aula 9 - Testes Estatísticos e Regressões"
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.align = "center")
```

## Introdução

```{r}
library(tidyverse)
library(nycflights13)
library(broom)
options(scipen=999)
# install.packages("stargazer")
library(stargazer)
```

```{r}
# install.packages("survival")
# install.packages("AER")
# install.packages("Amelia")
# install.packages("coda")
# install.packages("Formula")
# install.packages("geepack")
# install.packages("sandwich")
# install.packages("MatchIt")
# install.packages("maxLik")
# install.packages("MCMCpack")
# install.packages("quantreg")
# install.packages("survey")
# install.packages("VGAM")
```

```{r}
# install.packages("https://cran.r-project.org/src/contrib/Archive/Zelig/Zelig_5.1.6.tar.gz", repos=NULL, type="source")

library(Zelig)
```

```{r}
flights %>% sample_n(3000) %>% 
  pull(dep_delay) %>% 
  shapiro.test()
```

```{r}
flights %>% 
  ggplot() +
  geom_density(aes(x=dep_delay)) +
  xlim(0,100)
```

```{r}
teste_normalidade <- flights %>% sample_n(3000) %>% 
  pull(dep_delay) %>% 
  shapiro.test() %>% 
  tidy()
```


## Testes de Médias


```{r}
teste_media <- flights %>% filter(origin!="LGA") %>% 
  pull(dep_delay) %>%
  t.test(mu=13.4) %>% 
  tidy()
```

```{r}
teste_media %>% mutate(Variavel="Atraso na partida") %>% 
  ggplot() +
  geom_point(aes(x=Variavel, y=estimate)) +
  geom_hline(yintercept=13.4, lty=2, color="blue") +
  geom_errorbar(aes(x=Variavel, ymin=conf.low, ymax=conf.high), width=0.1)
```

## Comparando Médias

```{r}
flights %>% filter(origin!="LGA") %>% 
  t.test(dep_delay ~ origin, data=.) %>% 
  tidy()
```


## Testes de Correlação

```{r}
flights %>%
  cor.test( ~ dep_delay + dep_time, data = .) %>%
  tidy()
```
```{r}
flights %>% sample_n(1000) %>% 
  ggplot() +
  geom_point(aes(x=dep_time, y=dep_delay)) +
  geom_smooth(aes(x=dep_time, y=dep_delay), method="lm")
```

## Testes de Correlação de Variáveis Categóricas (Chi-squared)
```{r}
flights %>% select(origin, carrier) %>% 
  table() %>% 
  chisq.test() %>%
  tidy()
```

- Exercício 1: Testes Estatísticos

## Regressões Simples

```{r}
flights %>% lm(dep_delay ~ dep_time, data = .)
```

```{r}
flights %>% lm(dep_delay ~ dep_time, data=.) %>%
  summary()
```

```{r}
flights %>% lm(dep_delay ~ dep_time, data=.) %>%
  tidy()
```

```{r}
flights %>% lm(dep_delay ~ dep_time + origin, data=.) %>% tidy()
```

```{r}
flights %>% lm(dep_delay ~ dep_time + I(dep_time^2), data=.) %>% tidy()
```

## Tabelas de Resultados de Regressões

```{r, results='asis'}

flights %>% lm(dep_delay ~ dep_time + origin, data=.) %>%
  stargazer(type="html")
```

```{r, results='asis'}
flights %>% lm(dep_delay ~ dep_time + origin, data=.) %>%
  stargazer(type="html", title="Modelo de Atraso de Vôos",
            single.row = T, keep.stat = c("n"),
            dep.var.labels="Atraso",
            covariate.labels=c("Horário", "JFK", "LGA"),
            header=F, dep.var.caption="")
```

```{r, results='asis'}
reg1 <- flights %>% lm(dep_delay ~ dep_time, data=.)
reg2 <- flights %>% lm(dep_delay ~ dep_time + origin, data=.)

list(reg1, reg2) %>% stargazer(type="html")
```

## Gráficos de Efeitos Marginais das Regressões

```{r}
reg2 %>% tidy() %>%
  mutate(conf.lo=estimate-1.96*std.error,
         conf.hi=estimate+1.96*std.error) %>%
  filter(term!="(Intercept)") %>%
  ggplot() +
  geom_point(aes(x=term, y=estimate)) +
  geom_errorbar(aes(x=term, y=estimate, ymin=conf.lo, ymax=conf.hi), width=0.1)
```
 
## Modelos Alternativos



```{r}
flights %>% zelig(dep_delay ~ dep_time + origin, data=., model="ls")
```
```{r}
flights %>% mutate(atraso=case_when(dep_delay>0~1,
                                    TRUE~0)) %>%
  zelig(atraso ~ origin, data=., model="logit")
```

```{r}
flights %>% mutate(atraso_serio=case_when(dep_delay>240 ~ 1,
                                           TRUE ~ 0)) %>%
  group_by(origin, month, day) %>%
  summarize(atrasos_serios=sum(atraso_serio, na.rm=T))  %>%
  ungroup() %>% 
  zelig(atrasos_serios ~ origin, data=., model="poisson")
```

```{r results='asis'}
flights %>% mutate(atraso=case_when(dep_delay>0~1,
                                    TRUE~0)) %>%
  zelig(atraso ~ origin, data=., model="logit") %>%
  from_zelig_model() %>%
  stargazer(type="html")
```


## Previsões e Resíduos de Regressões


